wandb_version: 1

dataset_name:
  desc: null
  value: riseholme
dataset_path:
  desc: null
  value: ../datasets/riseholme_mvtec
epochs:
  desc: null
  value: 100
learning_rate:
  desc: null
  value: 0.005
batch_size:
  desc: null
  value: 30
image_size:
  desc: null
  value: 256
run:
  desc: null
  value: training
model:
  desc: null
  value: RD4AD
device:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    python_version: 3.12.3
    cli_version: 0.17.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1732299559
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 1
      - 16
      - 23
      4: 3.12.3
      5: 0.17.7
      8:
      - 5
      13: linux-x86_64
